using System.Collections.Concurrent;
using AstervoidsWeb.Services;

namespace AstervoidsWeb.Models;

/// <summary>
/// Represents a game session that members can join.
/// Detached lookup snapshots use the same model with independent state and SyncRoot;
/// mutating a snapshot does not change the live service state.
///
/// Synchronization model
/// ─────────────────────
/// All per-session mutations (join, leave, object create/update/delete/replace, object
/// ownership migration, and <see cref="LifecycleState"/> transitions) MUST be performed
/// while holding <see cref="SyncRoot"/>.  Read-only lookups (e.g. querying
/// <see cref="Members"/> or <see cref="Objects"/> counts for logging) do not require the
/// lock because <see cref="ConcurrentDictionary{TKey,TValue}"/> is itself thread-safe for
/// individual reads; however, any compound check-then-act sequence requires the lock.
///
/// Global indexes (<c>_connectionToMember</c>, <c>_memberToSession</c>, and the
/// <c>_sessions</c> dictionary in <c>SessionService</c>) use their own <c>_sessionLock</c>
/// for cross-session operations such as session creation and join capacity checks.
/// When both locks are needed the acquisition order is always
/// <c>_sessionLock</c> → <c>SyncRoot</c> to avoid deadlocks.
/// </summary>
public class Session
{
    /// <summary>
    /// Globally unique identifier for this session.
    /// </summary>
    public Guid Id { get; init; } = Guid.NewGuid();

    private string? _groupName;

    /// <summary>
    /// SignalR group name for this session (the string form of <see cref="Id"/>),
    /// cached so hot-path broadcasts do not re-allocate it on every send.
    /// Computed lazily; a concurrent first read may compute it twice, which is
    /// benign because both results are equal and reference publication is atomic.
    /// </summary>
    public string GroupName => _groupName ??= Id.ToString();

    /// <summary>
    /// Human-readable name for the session (generated by the configured ISessionNameGenerator).
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// Per-session synchronization root.  All session-local mutations (member
    /// add/remove, promotion, object create/update/delete, ownership migration,
    /// lifecycle transitions, and <see cref="LastMemberLeftAt"/> updates) must be
    /// performed while holding this lock.
    /// </summary>
    internal readonly object SyncRoot = new();

    /// <summary>
    /// Current lifecycle state of this session.
    /// Must only be read or written while holding <see cref="SyncRoot"/>.
    /// </summary>
    public SessionLifecycleState LifecycleState { get; set; } = SessionLifecycleState.Active;

    /// <summary>
    /// Thread-safe collection of members in this session.
    /// Key is the member's GUID.
    /// Individual reads are thread-safe without <see cref="SyncRoot"/>; compound
    /// check-then-act operations require <see cref="SyncRoot"/>.
    /// </summary>
    public ConcurrentDictionary<Guid, Member> Members { get; } = new();

    /// <summary>
    /// Thread-safe collection of objects in this session.
    /// Key is the object's GUID.
    /// Individual reads are thread-safe without <see cref="SyncRoot"/>; all mutations
    /// (including <see cref="SessionObject.Data"/> replacement and version bumps) require
    /// <see cref="SyncRoot"/>.
    ///
    /// Membership changes must go through <see cref="AddObject"/> / <see cref="RemoveObject"/>
    /// so the handle index stays consistent with this dictionary.
    /// </summary>
    public ConcurrentDictionary<Guid, SessionObject> Objects { get; } = new();

    /// <summary>
    /// Handle → object id index backing <see cref="TryGetObjectByHandle"/>.
    /// Maintained alongside <see cref="Objects"/> by <see cref="AddObject"/> and
    /// <see cref="RemoveObject"/>.
    ///
    /// Deliberately maps to the id rather than the object: lookups resolve through
    /// <see cref="Objects"/>, so a stale index entry can only fail to resolve — it can
    /// never revive an object that was removed from the authoritative dictionary.
    /// </summary>
    private readonly ConcurrentDictionary<int, Guid> _objectIdsByHandle = new();

    private int _lastObjectHandle;

    /// <summary>
    /// Allocates the next session-scoped object handle. Starts at 1 and only increases,
    /// so 0 is an unambiguous "no handle" sentinel and a handle is never reused within a
    /// session (a late update addressed to a deleted object cannot land on a new one).
    /// </summary>
    public int AllocateObjectHandle() => Interlocked.Increment(ref _lastObjectHandle);

    /// <summary>
    /// Adds an object and indexes its <see cref="SessionObject.Handle"/>.
    /// Must be called while holding <see cref="SyncRoot"/>.
    /// </summary>
    public bool AddObject(SessionObject obj)
    {
        if (!Objects.TryAdd(obj.Id, obj))
            return false;
        _objectIdsByHandle[obj.Handle] = obj.Id;
        return true;
    }

    /// <summary>
    /// Removes an object and its handle index entry.
    /// Must be called while holding <see cref="SyncRoot"/>.
    /// </summary>
    public bool RemoveObject(Guid objectId, out SessionObject? removed)
    {
        if (!Objects.TryRemove(objectId, out removed))
            return false;
        _objectIdsByHandle.TryRemove(removed.Handle, out _);
        return true;
    }

    /// <summary>
    /// Resolves a session-scoped handle to its object. Returns false for an unknown
    /// handle, or for one whose object has since been removed.
    /// Must be called while holding <see cref="SyncRoot"/> for compound check-then-act use.
    /// </summary>
    public bool TryGetObjectByHandle(int handle, out SessionObject? obj)
    {
        obj = null;
        return _objectIdsByHandle.TryGetValue(handle, out var objectId)
            && Objects.TryGetValue(objectId, out obj);
    }

    /// <summary>
    /// Timestamp when the session was created.
    /// </summary>
    public DateTime CreatedAt { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Arbitrary key-value metadata for this session, set by the creator at session
    /// creation time and immutable thereafter. Games can store any session-level
    /// configuration here (e.g. aspect ratio, game mode, map name).
    /// </summary>
    public Dictionary<string, object?> Metadata { get; init; } = new();

    /// <summary>
    /// Timestamp when the last member left the session (null if members are present).
    /// Used by the cleanup service to determine when to destroy empty sessions.
    /// Must only be read or written while holding <see cref="SyncRoot"/>.
    /// </summary>
    public DateTime? LastMemberLeftAt { get; set; }

    /// <summary>
    /// Server-assigned ordering number for session-level changes, not an expected-version precondition.
    /// Incremented on server promotion.  Must only be read or written while holding
    /// <see cref="SyncRoot"/>.
    /// </summary>
    public long Version { get; set; } = 1;

    internal Session CreateSnapshot()
    {
        lock (SyncRoot)
        {
            var snapshot = new Session
            {
                Id = Id,
                Name = Name,
                CreatedAt = CreatedAt,
                Metadata = SyncDataCloner.CloneDictionary(Metadata),
                LifecycleState = LifecycleState,
                LastMemberLeftAt = LastMemberLeftAt,
                Version = Version,
                _lastObjectHandle = _lastObjectHandle
            };
            // The unpublished copy has its own lock and handle index; neither
            // member/object records nor mutable payload containers are shared.
            lock (snapshot.SyncRoot)
            {
                foreach (var member in Members.Values)
                    snapshot.Members[member.Id] = new Member
                    {
                        Id = member.Id,
                        ConnectionId = member.ConnectionId,
                        Role = member.Role,
                        JoinedAt = member.JoinedAt,
                        SessionId = member.SessionId,
                        ReconnectToken = member.ReconnectToken,
                        EventSequence = Interlocked.Read(ref member.EventSequence)
                    };
                foreach (var obj in Objects.Values)
                    snapshot.AddObject(SyncDataCloner.CloneObject(obj));
            }
            return snapshot;
        }
    }
}
